import Footer from './components/Footer'
import NavBar from './components/NavBar'
import './globals.css'
import { Inter, Plus_Jakarta_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WenzeKin-plateforme de vente de produits de premier neccessiteux',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <NavBar/>
          <main className=''> 
            {children}
          </main>
         <Footer/>
      </body>
    </html>
  )
}

