import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { bannerQuery, productQuery } from '@/lib/Query'
import client from '@/lib/client'
import BannerHero from '@/components/BannerHero'

const inter = Inter({ subsets: ['latin'] })

export default function Home({productData, bannerData}) {
      const banner=bannerData[0]
  return (
    <>
      <Head>
        <title>WenzeKin-Le marché local a votre portée</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
      
          <BannerHero data={banner}/>      
              
        </div>            
      </main>
    </>
  )
}

export const getServerSideProps = async ()=>{
  

  const productData= await client.fetch(productQuery); 
  const bannerData= await client.fetch(bannerQuery); 

  return {
    props:{productData, bannerData}
  }
}